# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import myschool_pb2 as myschool__pb2


class MyStudentsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.student_details = channel.unary_unary(
                '/MyStudents/student_details',
                request_serializer=myschool__pb2.Student_ID.SerializeToString,
                response_deserializer=myschool__pb2.Student_Data.FromString,
                )
        self.student_classes = channel.unary_unary(
                '/MyStudents/student_classes',
                request_serializer=myschool__pb2.Student_ID.SerializeToString,
                response_deserializer=myschool__pb2.Class_data.FromString,
                )


class MyStudentsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def student_details(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def student_classes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyStudentsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'student_details': grpc.unary_unary_rpc_method_handler(
                    servicer.student_details,
                    request_deserializer=myschool__pb2.Student_ID.FromString,
                    response_serializer=myschool__pb2.Student_Data.SerializeToString,
            ),
            'student_classes': grpc.unary_unary_rpc_method_handler(
                    servicer.student_classes,
                    request_deserializer=myschool__pb2.Student_ID.FromString,
                    response_serializer=myschool__pb2.Class_data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MyStudents', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyStudents(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def student_details(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyStudents/student_details',
            myschool__pb2.Student_ID.SerializeToString,
            myschool__pb2.Student_Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def student_classes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MyStudents/student_classes',
            myschool__pb2.Student_ID.SerializeToString,
            myschool__pb2.Class_data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
