# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myschool.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emyschool.proto\"\'\n\nStudent_ID\x12\x19\n\x11student_Id_number\x18\x01 \x01(\t\"T\n\x0cStudent_Data\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12\x15\n\rDate_of_birth\x18\x04 \x01(\t\"6\n\nClass_data\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x14\n\x0cteacher_name\x18\x02 \x01(\t2h\n\nMyStudents\x12-\n\x0fstudent_details\x12\x0b.Student_ID\x1a\r.Student_Data\x12+\n\x0fstudent_classes\x12\x0b.Student_ID\x1a\x0b.Class_datab\x06proto3')



_STUDENT_ID = DESCRIPTOR.message_types_by_name['Student_ID']
_STUDENT_DATA = DESCRIPTOR.message_types_by_name['Student_Data']
_CLASS_DATA = DESCRIPTOR.message_types_by_name['Class_data']
Student_ID = _reflection.GeneratedProtocolMessageType('Student_ID', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT_ID,
  '__module__' : 'myschool_pb2'
  # @@protoc_insertion_point(class_scope:Student_ID)
  })
_sym_db.RegisterMessage(Student_ID)

Student_Data = _reflection.GeneratedProtocolMessageType('Student_Data', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT_DATA,
  '__module__' : 'myschool_pb2'
  # @@protoc_insertion_point(class_scope:Student_Data)
  })
_sym_db.RegisterMessage(Student_Data)

Class_data = _reflection.GeneratedProtocolMessageType('Class_data', (_message.Message,), {
  'DESCRIPTOR' : _CLASS_DATA,
  '__module__' : 'myschool_pb2'
  # @@protoc_insertion_point(class_scope:Class_data)
  })
_sym_db.RegisterMessage(Class_data)

_MYSTUDENTS = DESCRIPTOR.services_by_name['MyStudents']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STUDENT_ID._serialized_start=18
  _STUDENT_ID._serialized_end=57
  _STUDENT_DATA._serialized_start=59
  _STUDENT_DATA._serialized_end=143
  _CLASS_DATA._serialized_start=145
  _CLASS_DATA._serialized_end=199
  _MYSTUDENTS._serialized_start=201
  _MYSTUDENTS._serialized_end=305
# @@protoc_insertion_point(module_scope)
